config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products, only: [:index, :show, :edit, :update]
  resources :orders, except: [:edit, :update]
  post 'carts/cart_session/:id' => 'carts#cart_session', :as => 'carts_cart'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors.add attribute, (options[:message] || 'is not an email') unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end

class Order < ActiveRecord::Base
  include ActiveModel::Validations
  has_many :order_products
  has_many :products, :through => :order_products

  validates :buyer, :address, :email, presence: true
  validates :email, presence: true, email: true
end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base

  belongs_to :product
  belongs_to :order

end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ProductImageUploader

  paginates_per 2
  has_many :order_products
  has_many :orders, :through => :order_products

  validates :name, :description, :price, presence: true

  def convert_price(exchange_rate)
    self.price = self.price * exchange_rate
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/admins/confirmations_controller.rb
class Admins::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admins/omniauth_callbacks_controller.rb
class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admins/passwords_controller.rb
class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/registrations_controller.rb
class Admins::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/admins/unlocks_controller.rb
class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def cart_session
    session[:cart] ||= []
    session[:cart] << params[:id]
    redirect_to products_path
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :require_login, only: [:index, :destroy]
  before_action :find_order, only: [:show, :destroy]

  def index
    @orders = Order.all
  end

  def show
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    session[:cart].each do |el|
      @order.products << Product.find(el)
    end
    respond_to do |format|
      if @order.save
        format.html { redirect_to products_path, notice: 'Order was successfully created.' }
      else
        format.html { redirect_to products_path, notice: 'Sorry, your order is not issued. Please try again.' }
      end
    end
  end

  def destroy
    @order.destroy
    session[:cart] = nil
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def find_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:buyer, :address, :email)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update]

  def index
    @products = Product.order(:name).page params[:page]
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  private

  def find_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :image, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/application/_authentication.html.erb
<div class="authentication">
<% if signed_in? %>
    Signed in as: <%= current_user.email %>
    <%= button_to 'Sign out', sign_out_path, method: :delete %>
<% else %>
    <%= link_to 'Sign in', sign_in_path %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StoreRails</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">

<p class="notice"><%= notice %></p>

<%= render 'authentication' %>

<%= yield %>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
    <div>
      <%= f.label :buyer %><br>
      <%= f.text_field :buyer, size: 40 %>
    </div>
    <div>
      <%= f.label :address %><br>
      <%= f.text_area :address, rows: 3, cols: 40 %>
    </div>
    <div>
      <%= f.label :email %><br>
      <%= f.email_field :email, size: 40 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Email</th>
    <th>Products</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @orders.each do |order| %>
      <tr>
        <td><%= order.buyer %></td>
        <td><%= order.address %></td>
        <td><%= order.email %></td>
        <td>
          <% order.products.each do |product| %>
              <%= product.name %>
          <% end %>
        </td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to main', products_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back to main', products_path %>

app/views/orders/show.html.erb
<p>
  <strong>Name buyer:</strong>
  <%= @order.buyer %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Orders:</strong>
  <% @order.products.each do |product| %>
      <%= product.name %>
  <% end %>
</p>

<%= link_to 'Back to main', products_path %><br/>
<%= link_to 'Back to orders', orders_path %>

app/views/products/_form.html.erb
<%= form_for @product, html: {multipart: true} do |f| %>
    <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% @product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description, rows: 8 %>
    </div>
    <div class="field">
      <%= image_tag(@product.image.small_image.url) %>
      <br>
      <%= f.file_field :image %>
    </div>
    <div class="field">
      <%= f.label :price %><br>
      <%= f.text_field :price %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %>
<%= link_to 'Back to main', products_path %>

app/views/products/index.html.erb
<h1>Assortment of products</h1>
<table>
  <%= paginate @products %>
  <% @products.each do |product| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td>
          <%= image_tag(product.image.small_image.url) %>
        </td>
        <td class="list_description">
          <dl>
            <dt><%= product.name %></dt>
            <dd><%= product.description %></dd>
            <dd><%= number_to_currency(product.price) %></dd>
          </dl>
        </td>
        <td class="list_actions">
          <%= link_to 'Show', product %><br/>
          <br/>
          <%= link_to 'Edit', edit_product_path(product) %><br/>
          <br/>
          <%= button_to 'Add to cart', carts_cart_path(product.id) %><br/>
        </td>
      </tr>
  <% end %>
</table>
<br/>

<%= link_to 'Place an order', new_order_path %><br/>
<% if signed_in? %>
    <%= link_to 'Back to orders', orders_path %>
<% end %>

app/views/products/show.html.erb
<p>
  <strong>Name product:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= image_tag(@product.image.large_image.url) %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@product.price) %>
</p>

<%= link_to 'Back to main', products_path %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t('.title') %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t('.sign_in'), sign_in_path %>
    </div>
  <% end %>
</div>